Reactive `always_update`
Textualize/textual pull request #1014
Opened 2022-10-25 13:40 UTC by darrenburns

Adds `always_update` to `reactive`.

2022-10-29 07:30 UTC, davep approved these changes

2022-10-29 19:04 UTC, willmcgugan requested changes
Request for doc update

2022-10-29 19:04 UTC, willmcgugan commented on docs/guide/reactivity.md
> +!! warning
I don't think this is worthy of a warning. Suggest we promote this to another paragraph, with a new sub-heading.

2022-10-31 13:05 UTC, willmcgugan approved these changes

2022-10-31 13:05 UTC, merged