Support easier widget "support classes" importing
Textualize/textual pull request #1637
Opened 2023-01-23 11:07 UTC by davep

This PR implements the suggested solution for the requirement detailed in #1589. Quite simply, for those widgets that have non-widget support classes that the using-developer needs access to, have a parallel non-under-prefixed version of the code that imports and "reexports" the support classes.

As such, all this PR does is implement this approach for the widgets that seen to need it. The only one that required it at the moment was `DataTable`, so that `Column` and `Row` can be seen by the calling code. `TreeNode` already had an approach to this but for the sake of completeness I've added parallel support for this newer convention.

We may want to think about deprecating `widgets.TreeNode`.

2023-01-23 15:16 UTC, rodrigogiraoserrao approved these changes

2023-01-23 17:05 UTC, willmcgugan requested changes
Could you remove references to TreeNode from the lazy-loading "widgets" while you are here.

2023-01-23 17:06 UTC, davep commented
> Could you remove references to TreeNode from the lazy-loading "widgets" while you are here.

Yup, happy to. Was holding that for a followup PR but if we're happy for the breaking change now that's my preference too. :-)

2023-01-23 17:45 UTC, davep commented
`TreeNode` now modified to follow this PR: https://github.com/Textualize/textual/pull/1637/commits/4adfe69ec90499a50a966ae655c05276f14a6acf

2023-01-25 08:05 UTC, rodrigogiraoserrao approved these changes

2023-01-25 10:53 UTC, merged