Add support for a method of expanding/collapsing all tree nodes from a given node down
Textualize/textual pull request #1644
Opened 2023-01-23 17:29 UTC by davep

WiP.

See #1430.

2023-01-24 10:37 UTC, rodrigogiraoserrao approved these changes
The changes look good to me.
I have two questions, though:

 1. I'd expect the `collapse_all` default value to also be `False` so that, by default, collapsing a node will not mess with the collapsed/expanded state of children. E.g., like VS Code does in the built-in file explorer.
 2. What's the `self._tree._invalidate()`? Is there a "local" version of that that we can call when we only change the state of a single node, i.e. when the recursive calls are skipped?

2023-01-24 10:40 UTC, davep commented
> 1. I'd expect the `collapse_all` default value to also be `False` so that, by default, collapsing a node will not mess with the collapsed/expanded state of children. E.g., like VS Code does in the built-in file explorer.

Not sure that's a question. :-P

But, yes, you're right, that (and toggle) is a typo, so good catch.

> 2. What's the `self._tree._invalidate()`? Is there a "local" version of that that we can call when we only change the state of a single node, i.e. when the recursive calls are skipped?

I'm not sure I understand this question though, could you elaborate?

2023-01-24 10:43 UTC, rodrigogiraoserrao commented
> Not sure that's a question. :-P

It's not, I started typing with one formulation in mind and ended up writing something different 😆 

> I'm not sure I understand this question though, could you elaborate?

I'm assuming the call to `invalidate` is to invalidate some cache or to flag the need for redrawing the tree, or something of the sorts. When there are no recursive updates, can you not make a similar call that just says "hey, invalidate just this node"? Do you need to have the same `invalidate` call regardless of whether you updated one node or 1000 nodes?

2023-01-24 10:46 UTC, darrenburns commented
The "toggle children" behaviour seems weird to me - if I have some children open those will be closed, and the children that are closed will be open?

Would it make more sense to just toggle the parent, then walk the children and make sure their state _matches_ that of the parent?

2023-01-24 10:47 UTC, davep commented
> When there are no recursive updates, can you not make a similar call that just says "hey, invalidate just this node"? Do you need to have the same `invalidate` call regardless of whether you updated one node or 1000 nodes?

Sorry, I'm still not sure I'm following the question. `self._tree._invalidate` invalidates the tree, not the node, so it only needs to be done the once no matter if you change the expanded state of a single node or 1000s of nodes.

2023-01-24 10:57 UTC, davep commented
Taking this back to a draft PR for a wee while as I can see there's questions about user experience and expectation to address.

2023-01-24 11:10 UTC, davep commented
Right, a36583612c78d21fe8bbd2cce2bb6da2caf70fe8 takes the toggle from being "technically correct" to, erm... actually useful? 😄

2023-01-24 11:34 UTC, rodrigogiraoserrao approved these changes
Nice adding the `*` to force the `x_all` parameters to be keyword only.

2023-01-25 11:00 UTC, willmcgugan commented on src/textual/widgets/_tree.py
> +    def expand(self, *, expand_all: bool = False) -> None:
There's some redundancy in the parameter name here `exapand_all`, and friends.

At the moment to expand all nodes you would do this:

```python
node.expand(expand_all=True)
```

Two mentions of "expand". But its not like there is any ambiguity re what the "all" refers to.

How about this?

```python
node.expand(all=True)
```

2023-01-25 18:06 UTC, davep commented
Todo: we've decided to break these out into different methods; `expand` vs `expand_all`, etc.

2023-01-27 09:08 UTC, willmcgugan requested changes
Looks great. Could use tests.

2023-01-27 09:23 UTC, davep commented
Cool, now we're happy with this I'll add them.

2023-01-27 13:31 UTC, davep commented
Tests for all the `TreeNode` expand/collapse/toggle methods now added.

2023-01-30 15:27 UTC, merged