Fix issue with tabbed content underline
Textualize/textual pull request #2274
Opened 2023-04-12 21:14 UTC by rodrigogiraoserrao

I did some investigation around #2229 and I figured out the issue is related to the fact that it takes a lot of time to swap in and out the contents of the tabbed content.
Commenting out this line makes the issue go away:

https://github.com/Textualize/textual/blob/c249548c43f6831db76d59aba5cc10c600335afa/src/textual/widgets/_tabbed_content.py#L188

That's called when the message `Tabs.TabActivated` is handled in `TabbedContent`, and that message is coming from `Tabs.watch_active`.

A simple fix would be to throttle `Tabs.watch_active` so that it doesn't get called _too_ often.
That is what this PR does, and merging it will close #2229.

Another possible solution, that is more involved, is to add a task-based mechanism around swapping the visible sub-widget of the `ContentSwitcher` in `ContentSwitch.watch_current`, such that when we schedule a new switch, old ones get thrown away.

2023-04-13 08:52 UTC, willmcgugan requested changes
This feels like it might be masking the error, rather than fixing it. I don't think you guarantee that time mechanism won't fail on a slower machine or with faster key repeat.

Have you established why this occurs?

2023-04-13 08:52 UTC, willmcgugan commented on src/textual/widgets/_tabs.py
> +        print(tabs[new_tab_index].id or "")
Debug print?

2023-04-13 14:25 UTC, rodrigogiraoserrao commented
> This feels like it might be masking the error, rather than fixing it. [...]

Sadly, I share this sentiment.

> Have you established why this occurs?

Not really... I will dig some more.

2023-04-17 15:41 UTC, rodrigogiraoserrao commented
Closing this because the actual fix (coming soon) is unrelated to this throttling attempt.

2023-04-17 15:41 UTC, closed without merging