Refactor Tree Messages
Textualize/textual pull request #2602
Opened 2023-05-18 04:02 UTC by aaronst

An attempt to address #2528 and #2529 as suggested by @davep.

- Changed `Message.control` to a property
- Removed the `tree` parameter from:
  - `Tree.NodeCollapsed`
  - `Tree.NodeExpanded`
  - `Tree.NodeHighlighted`
  - `Tree.NodeSelected`
  - `DirectoryTree.FileSelected`
- Changed the above's `control` to return `self.node.tree`.

I was not entirely following what changes needed to be made to the `@on` decorator, but I believe the rest is there. Additionally, I was getting a type error for `DirectoryTree.FileSelected.control` because `self.node.tree` is a `Tree[DirEntry]` vs a `DirectoryTree`. Not sure if that matters so I wanted to raise it here.

Hope this helps, happy to get it finished with a little more guidance.

2023-05-22 09:34 UTC, willmcgugan commented
Looks good to me. @davep thoughts?

2023-05-22 09:35 UTC, davep commented
@willmcgugan Aye, I like what I see here!

2023-05-22 09:39 UTC, willmcgugan requested changes
Looks good. Would you mind adding a brief CHANGELOG entry.

2023-05-22 22:49 UTC, aaronst commented on src/textual/widgets/_select.py
> +            self.widget = widget
Will do!

2023-05-22 23:03 UTC, aaronst commented
> Looks good. Would you mind adding a brief CHANGELOG entry.

Added!

2023-05-24 19:10 UTC, davep commented
I believe this should also fix #2648.

2023-05-25 12:48 UTC, willmcgugan approved these changes
LGTM.

2023-05-25 12:48 UTC, merged