Added suggester to complete input multiply times by last entered word
Textualize/textual pull request #2881
Opened 2023-07-03 01:13 UTC by lakdemon

**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

2023-07-04 14:53 UTC, rodrigogiraoserrao commented
Hey @lakdemon, thanks for your PR.
Do you mind giving me a bit more of context as to what your PR is trying to do, what the rationale for adding this is, etc?

Thanks!

2023-07-05 22:38 UTC, lakdemon commented
I use this class in my application and I think it might be useful to have it in textual.
The matter is that SuggestFromList can add a phrase only once at the beginning of input.
For example:
**"S"**_elect something from ..._
**"I"**_nput data into ..._
This class can offer a hint for each word as you type.
For example dictionary name
**"S"**_elect_
**"Select f"**_rom_
**"Select from t"**_able_

This is much more convenient in some cases and may come in handy later for TextArea inputs i think.
If someone is interested in this, then I can try to add tests and a description for the PR

2023-07-05 22:52 UTC, lakdemon commented
![suggestion_example](https://github.com/Textualize/textual/assets/26528966/08735a8c-1a17-426e-9186-7dfdd2a8d414)

2023-07-11 09:23 UTC, rodrigogiraoserrao commented
@willmcgugan I need your input on this!
Pun intended!

2023-07-11 09:47 UTC, rodrigogiraoserrao commented
> I'm afraid I don't quite grasp what this is doing over the existing suggester. I would need example(s)

See the GIF here: https://github.com/Textualize/textual/pull/2881#issuecomment-1622640222

This suggester only completes the last word whereas the suggester that is already implemented completes the whole input.

2023-07-11 09:55 UTC, willmcgugan commented
Sounds like a good idea in principle. The PR would need a bit of work to go in to the core library.

2023-07-11 09:56 UTC, rodrigogiraoserrao commented
> The PR would need a bit of work to go in to the core library.

I'm happy to work with @lakdemon to get the PR in a good state for us to review.

2023-07-11 09:59 UTC, willmcgugan requested changes

2023-07-11 09:59 UTC, willmcgugan commented on src/textual/suggester.py
> +            for idx, suggestion in enumerate(self._for_comparison):
Probable shouldn't be using "private" data here. Suggest directly suggesting from `Suggester`.

2023-07-11 09:59 UTC, willmcgugan commented on src/textual/suggester.py
> +            for idx, suggestion in enumerate(self._for_comparison):
We have a policy of no abbreviations, so `index` would be preferred over `id`

2023-07-11 09:59 UTC, willmcgugan commented on src/textual/suggester.py
> +    """
Docstring could use more detail. See other docstrings for inspiration.

2023-10-05 14:06 UTC, rodrigogiraoserrao commented
Hey @lakdemon, are you happy to go over the requested changes or do you want to close this PR?

2023-10-09 11:57 UTC, willmcgugan commented
Closing for now. Assumed stale.

My gut feeling is that it doesn't necessarily belong in the core library.

2023-10-09 11:57 UTC, closed without merging