WIP Reset css
Textualize/textual pull request #294
Opened 2022-02-17 15:17 UTC by willmcgugan

2022-02-17 15:43 UTC, willmcgugan commented on src/textual/layout.py
> +        log(update)
Shows the regions that are updating in the logs. Will likely remove in the future, but useful for now.

2022-02-17 15:44 UTC, willmcgugan commented on src/textual/css/stylesheet.py
> +        """Replace style rules to a node, animating as required.
This code was tricky to get right. There are a few things going on here. Let me know if you want to go over it.

2022-02-21 14:04 UTC, darrenburns requested changes

2022-02-21 14:05 UTC, willmcgugan commented on src/textual/_animator.py
> +            final_value (Any, optional): The final value, or ellipsis if it is the same as ``value``. Defaults to ....
Replaces the value at the end of the animation. This functionality is currently broken.

2022-02-21 14:07 UTC, willmcgugan commented on src/textual/css/styles.py
> +    def get_render_rules(self) -> RulesMap:
It's a quite specific kind of RulesMap. Can't think of a better name right now...

2022-02-21 14:09 UTC, willmcgugan commented on src/textual/css/stylesheet.py
> +        # Alias styles and base styles
Just means creating another name for something. So it is called `styles` rather than `node.styles`.

2022-02-21 14:11 UTC, willmcgugan commented on src/textual/_animator.py
> +            final_value (Any, optional): The final value, or ellipsis if it is the same as ``value``. Defaults to ....
Going to look at the final value issue and test for the animation syste,.

2022-02-21 14:19 UTC, merged