method for reloading single node of DirectoryTree
Textualize/textual pull request #2988
Opened 2023-07-22 14:45 UTC by gergely-elias

**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

2023-07-22 20:48 UTC, rodrigogiraoserrao requested changes
This is headed in the correct direction!
Just a couple of small changes, please!

2023-07-22 20:48 UTC, rodrigogiraoserrao commented on tests/tree/test_directory_tree_reload_node.py
This test looks great!

I'm just going to ask if we can avoid writing inside the files after creating them.
It saves us just a little bit of time! ⏩

2023-07-22 20:48 UTC, rodrigogiraoserrao commented on tests/tree/test_directory_tree_reload_node.py
> +class MyDirectoryTree(DirectoryTree):
You can use `DirectoryTree` directly! 😃

2023-07-23 03:53 UTC, gergely-elias commented
> This is headed in the correct direction! Just a couple of small changes, please!

Thanks for the comments, I'm about to push updates.
One thing I noticed is that there is a failing test case affecting tabs on windows/python3.8 setup.
I was wondering how stable the tests are and if I should look into that specific case.

2023-07-23 07:54 UTC, davep commented on src/textual/widgets/_directory_tree.py
> +    def clear_subtree(self, node: TreeNode[DirEntry]) -> DirectoryTree:
I think I'd have this typed to return `Self`.

2023-07-23 07:54 UTC, davep commented on src/textual/widgets/_directory_tree.py
> +    ) -> DirectoryTree:
I think I'd have this typed to return `Self`.

2023-07-23 08:18 UTC, rodrigogiraoserrao commented
@gergely-elias yeah some of our tests are a bit flaky; yesterday I noticed a failing test in this PR and it was completely unrelated to you. I re-ran it and it passed.
I'll let you take a look at @davep's comments and then I'll run CI again so we can merge your PR! 🚀

2023-07-23 12:08 UTC, gergely-elias commented
Thanks @davep & @rodrigogiraoserrao.
I've pushed another commit, in which the import is behind an if - just like the way it is in the parent class.
But I saw that in other classes you import it without such condition, and it wasn't clear if there is a reason for this.

Let me know if it is fine as it is now or should be reworked.

2023-07-23 12:46 UTC, rodrigogiraoserrao approved these changes
Looks good to me! 🚀

2023-07-26 14:20 UTC, willmcgugan requested changes
It's probably best to add some utility methods on the base case as needed here.

2023-07-27 19:35 UTC, gergely-elias commented on src/textual/widgets/_directory_tree.py
> +        node = TreeNode(
you're right, the second argument should be the parent node, and not `None`

2023-07-28 19:36 UTC, gergely-elias commented on tests/tree/test_directory_tree_reload_node.py
> +async def test_directory_tree_reload_node(tmp_path) -> None:
I did both break it down into two cases and added some comments. Let me know if you still think the tests should be improved.

2023-07-28 19:39 UTC, gergely-elias commented on src/textual/widgets/_directory_tree.py
> +        self._line_cache.clear()
I noticed the base class already has an `invalidate_cache` method, which needs just a little bit more than needed here, so in the end I did not use that one. On the other hand - as far as I can see - calling that one would also be an option here, so maybe you'd prefer to be this done with that.

Also I did not implement a utility method to increase `self._updates`, looked like somewhat of an overkill. But again, let me know if you'd prefer it being done like that.

2023-08-07 11:07 UTC, rodrigogiraoserrao approved these changes
After addressing Will's comments, the PR looks good to me.

Sorry for the time you've been waiting. We'll come back to you ASAP.

2023-08-07 13:38 UTC, gergely-elias commented
@rodrigogiraoserrao no worries
I think functionality wise this PR is complete, but am not sure if I really follow all your design conventions - so if reorganizing the parts regarding cache clearing is desired, please don't hesitate to tell

2023-08-08 15:26 UTC, willmcgugan requested changes
Looks good. Just one super trivial request.

2023-08-08 15:26 UTC, willmcgugan commented on src/textual/widgets/_tree.py
> +    def clear_line_cache(self) -> None:
This should be private, i.e. prefixed with `_`. It's not something that the dev needs to know about generally.

2023-08-09 05:42 UTC, gergely-elias commented
@rodrigogiraoserrao @willmcgugan
all review requests have been addressed, please approve

2023-08-09 09:00 UTC, rodrigogiraoserrao commented
@gergely-elias thank you so much for all your work and patience!
I'm waiting for the tests to pass ([relevant xkcd](https://xkcd.com/303/)) and I'll merge it :)

2023-08-09 13:16 UTC, willmcgugan approved these changes
LGTM!

2023-08-09 13:23 UTC, merged