Fix for DataTable race-condition crash
Textualize/textual pull request #3211
Opened 2023-08-31 03:29 UTC by jamespan

**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

2023-09-04 14:50 UTC, rodrigogiraoserrao requested changes
Hey there, thanks for opening this PR.

I added a small request after a quick look at your changes.
(By the way, thanks for adding a test!)

2023-09-07 02:19 UTC, jamespan commented on tests/test_data_table.py
> +async def test_table_update_remove_on_idle():
Docstring added.

2023-09-12 12:17 UTC, rodrigogiraoserrao approved these changes

2023-09-13 14:12 UTC, willmcgugan commented
@darrenburns Your call on this one...

2023-09-13 15:56 UTC, darrenburns commented
I wonder if adding the following to `remove_row` is all that's needed here.

```python
        for column_key in self._data.get(row_key):
            self._updated_cells.discard(CellKey(row_key, column_key))
```

This ensures that when we remove a row, then any cells that were contained within that row and awaiting a new width calculation are discarded before `on_idle` comes around.

2023-10-05 14:55 UTC, willmcgugan commented
I think we are going to go with an alternative solution. Thanks for bringing this to our attention @jamespan

2023-10-05 14:55 UTC, closed without merging