Tweak progress bar docs.
Textualize/textual pull request #3286
Opened 2023-09-12 11:54 UTC by rodrigogiraoserrao

There is no good reason as to why the progress bar can't be set back to its indeterminate state (and you could actually do it with code) so this removes the docstring that says that a progress bar can't go back to its indeterminate state.

Related issue: #3268
Related Discord message: https://discord.com/channels/1026214085173461072/1033754296224841768/1149742624002023594

2023-09-15 09:47 UTC, willmcgugan requested changes
You can also set the total with  the `update`, and it look like that prohibits setting None.

2023-09-15 10:10 UTC, rodrigogiraoserrao commented
> You can also set the total with the `update`, and it look like that prohibits setting None.

It's not that it prohibits. It's the _only_ way to design such an `update` method which can update multiple things at once. It's just like how `update` works for rich progress bars [docs](https://rich.readthedocs.io/en/stable/reference/progress.html#rich.progress.Progress.update) and it's written clearly that `update(some_key=some_value)` will only have any effect if `some_value` is not `None`.

2023-09-15 10:11 UTC, rodrigogiraoserrao commented
I can get rid of the method `update` if it's causing more confusion that doing good.

2023-09-20 12:50 UTC, willmcgugan approved these changes

2023-09-20 12:51 UTC, merged