Add Document.get_index(location)
Textualize/textual pull request #3410
Opened 2023-09-27 08:55 UTC by davidbrochart

**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

2023-09-30 16:14 UTC, davidbrochart commented
I think these methods could be useful when some document changes come from a system which is not `Location`-aware, but only reports changes pointing to raw indexes in the document content, like in collaborative editing.

2023-10-09 10:02 UTC, willmcgugan commented
@darrenburns Could you have a look at this one pls.

2023-10-18 10:13 UTC, darrenburns requested changes

2023-10-18 10:13 UTC, darrenburns commented on src/textual/document/_document.py
> +    def get_index_from_location(self, location: Location) -> int:
I can see why both of these would be useful. Would you mind writing a few tests for them?

Also, we have a policy of avoiding shorthand variable names where possible, so if you wouldn't mind renaming `col` -> `column`, `i` -> `line_index`, etc. that'd be appreciated too.

2023-10-18 11:25 UTC, davidbrochart commented
Thanks for the review @darrenburns, I made the changes, rebased and added some tests.

2023-10-19 19:08 UTC, darrenburns commented
Thanks @davidbrochart, could you also update the changelog?

2023-10-19 20:28 UTC, davidbrochart commented
Done.

2023-10-24 16:51 UTC, darrenburns approved these changes

2023-10-24 16:51 UTC, merged

2023-10-24 16:51 UTC, darrenburns commented
Thanks!