Fix documentation warnings
Textualize/textual pull request #3425
Opened 2023-09-28 23:08 UTC by guy-av

**Please review the following checklist.**

- [x] Updated documentation
- [ ] For some reason `textual.app.App.compose()` doesn't seem to appear in the reference section of the docs hence breaking a specific link on the `App basics` page.

Resolves #2699

2023-09-29 07:17 UTC, rodrigogiraoserrao commented
The issue with the compose method is that it is excluded from the docs, but if it is linked from elsewhere, we either link to something else or we make sure that App.compose is documented as well.
Look at the api documentation for Widget, where we override some methods that are otherwise excluded via the documentation configuration.

2023-10-04 21:07 UTC, guy-av commented
@davep made sure the filters in `api/app.md` match those of the widgets, filtering out only `__init__` and private members. Will you take another look please?

2023-10-04 21:09 UTC, davep commented on mkdocs-nav.yml
> +          - "widgets/toast.md"
My memory is hazy, but I'm sure we left toast out of the widget list as it's not really a "public-facing" widget; it's more of an internal support widget for the default implementation of `App.notify`.

2023-10-04 21:11 UTC, davep commented on mkdocs-nav.yml
> +      - "api/content_switcher.md"
Given that `ContentSwitcher` is within the widgets, I'm wondering why there is an `api/content_switcher.md` at all.

2023-10-04 21:14 UTC, davep commented
> made sure the filters in api/app.md match those of the widgets, filtering out only __init__ and private members. Will you take another look please?

@guy-av Forgive me, I may have missed some context here. Another look? Is this something I've looked at before?

2023-10-04 21:16 UTC, guy-av commented
> > made sure the filters in api/app.md match those of the widgets, filtering out only **init** and private members. Will you take another look please?
> 
> @guy-av Forgive me, I may have missed some context here. Another look? Is this something I've looked at before?

Actually didn't mean to tag you 😅 sorry about that.
Thanks for reviewing though!

2023-10-09 10:13 UTC, willmcgugan requested changes

2023-10-09 10:13 UTC, willmcgugan commented on src/textual/widgets/_option_list.py
> +    def get_option_index(self, option_id: str):
Can we have a return type here.

2023-11-27 10:41 UTC, rodrigogiraoserrao commented
I'm closing this as it got stale and was superseded by the PR linked above.

2023-11-27 10:41 UTC, closed without merging