Redirect standard output to devtools server
Textualize/textual pull request #385
Opened 2022-04-12 15:26 UTC by darrenburns

Data printed using the builtin `print` will be sent over to the devtools, if you're connected to them.

The behaviour of the file-like object that redirects this output mirrors the behaviour of stdout (line buffering).

There's some additional logic in here to handle calls like `print(1, 2, 3)`. A call to print with multiple arguments results in Python calling the redirectors `write` method 3 times. We batch these calls into 1 since they're made from the same `print` statement call. This means in the devtools you only see 1 timestamp/log entry for a single print function call (as expected).

2022-04-12 15:32 UTC, willmcgugan commented on src/textual/app.py
> +                self.console = Console(file=sys.__stdout__)
Probably, but at least this ensures that we're not using any kind of wrapped file.

2022-04-13 14:13 UTC, willmcgugan commented
@darrenburns Sorry a created a merge conflict for you 😈

2022-04-13 16:05 UTC, willmcgugan requested changes

2022-04-13 17:22 UTC, tusharsadhwani commented on src/textual/devtools/client.py
> +    def log(self, log: DevtoolsLog):
I think it's about time you setup mypy on CI. pre-commit.ci perhaps?

2022-04-14 10:08 UTC, darrenburns commented on src/textual/devtools/client.py
> +    def log(self, log: DevtoolsLog):
Good catch, re-added.

@tusharsadhwani I ran `mypy` but it doesn't complain about this by default. We will add `mypy` eventually, but the code is in flux and it won't pass typechecking at the moment. We'll get there eventually :)

2022-04-14 10:39 UTC, darrenburns commented
Now closes #393 too

2022-04-14 10:59 UTC, willmcgugan approved these changes
LGTM Nicely done with the line buffering.

2022-04-14 10:59 UTC, merged