Improve nested tcss
Textualize/textual pull request #4040
Opened 2024-01-17 17:19 UTC by rodrigogiraoserrao

Partially fixes #3969 and #3999.

See #4039 for what's left.

2024-02-01 10:59 UTC, willmcgugan commented
@rodrigogiraoserrao Please add some detail on what you fixed (and how). The issues you linked to don't make it clear what work is outstanding. The title is also rather vague -- what was improved?

2024-02-07 14:17 UTC, rodrigogiraoserrao commented
@willmcgugan changed the title, expanded the description, and clarified the [outstanding issue 4039](https://github.com/Textualize/textual/issues/4039).

2024-02-07 15:42 UTC, darrenburns requested changes
I've added a couple more comments - sorry!

2024-02-07 16:32 UTC, rodrigogiraoserrao commented
@darrenburns ignored! But did you review at all? It doesn't show neither an accepted nor a change requested.

2024-02-08 14:49 UTC, willmcgugan commented
@rodrigogiraoserrao  Your tests are essentially snapshot tests. They are as likely to catch *any* change to the tokenizer, as they are to catch errors.

Suggest we have a test which takes CSS then checks that the expected styles are set on the widget. If that breaks in the future we know that it is a genuine issue, and not just that we have made an inconsequential changed to the tokenizer.

2024-02-08 16:55 UTC, rodrigogiraoserrao commented
> @rodrigogiraoserrao Your tests are essentially snapshot tests. They are as likely to catch _any_ change to the tokenizer, as they are to catch errors.

Isn't that true of all tokenizer tests?

> Suggest we have a test which takes CSS then checks that the expected styles are set on the widget.

Then, doesn't that mean the test can fail for many different reasons that are completely orthogonal to the thing I'm trying to test, which is that the tokenizer knows what to do with these tokens?

2024-02-13 16:56 UTC, willmcgugan commented
> Isn't that true of all tokenizer tests?

Yes, which is why we don't need more.

> Then, doesn't that mean the test can fail for many different reasons that are completely orthogonal to the thing I'm trying to test, which is that the tokenizer knows what to do with these tokens?

That's not what we should be testing. We should be testing the CSS that didn't work before, and now does. The output from the tokenizer does not prove that the CSS is processes as expected.

2024-02-15 14:10 UTC, rodrigogiraoserrao commented
@willmcgugan got it. See 3c18e47.
This is ready to be reviewed.

2024-02-15 16:33 UTC, darrenburns commented on tests/css/test_nested_css.py
> +    # css = "Screen{Label{background:red;}background:green;}"
```suggestion
```

2024-02-15 16:35 UTC, darrenburns approved these changes
Looks good!

2024-02-15 16:43 UTC, merged