[colors] Add management of named Web colors to our CSS processing, prefix ANSI ones with `ansi_`
Textualize/textual pull request #443
Opened 2022-04-28 13:26 UTC by DrBenton

Submitting this PR as a quick preview, since I realised that it brings an inconsistency issue between Rich and Textual: if we prefix all ANSI colour names with  `ansi_` in Textual we may have unexpected behaviours when we use the underlying Rich primitives in Textual - as Rich still have only ANSI colours, without the prefix in their names.

In the Textual DevTools for example, we use `padding = Segment("▌", Style.parse("bright_magenta"))` : I initially replaced _"bright_magenta"_ with _"ansi_bright_magenta"_ there, but doing so breaks the DevTools because the `Style` class is a Rich component, not a Textual one :grimacing: 

What do you folks think? @willmcgugan @darrenburns

2022-04-28 14:04 UTC, DrBenton commented
@willmcgugan As discussed, I merged the first 16 ANSI colors with the named Web ones, and added the `transparent` pseudo-colour [eedec6c](https://github.com/Textualize/textual/pull/443/commits/eedec6c8630af01c83ae905ac6b45d8071faa782) :slightly_smiling_face:

2022-04-29 09:46 UTC, willmcgugan requested changes
Great. Just a typing request.

2022-04-29 09:46 UTC, willmcgugan commented on src/textual/_color_constants.py
> +COLOR_NAME_TO_RGB: dict[str, tuple[int, int, int] | tuple[int, int, int, int]] = {
The alpha component is a float between 0 and 1

2022-04-29 09:47 UTC, willmcgugan commented on src/textual/_color_constants.py
> +COLOR_NAME_TO_RGB: dict[str, tuple[int, int, int] | tuple[int, int, int, int]] = {
NM fixed in merge

2022-04-29 09:51 UTC, willmcgugan approved these changes

2022-04-29 09:52 UTC, willmcgugan commented
👍

2022-04-29 09:52 UTC, merged