Added waring when message handling take long time
Textualize/textual pull request #4905
Opened 2024-08-20 13:40 UTC by Zimzozaur

### This PR resolves #4895 
cc @willmcgugan

**Implemented Features:**

- Warning for Slow Handlers: Logs a warning if a message handler takes longer than 500ms to process.
- Debug Mode Only: Warnings are enabled only in debug mode to avoid unnecessary overhead in production.
- Configurable Threshold: The time threshold before a warning is issued can be set via the `TEXTUAL_SLOW_THRESHOLD_MS` environment variable.

**Known Limitations:**

Currently, the warning is logged only after the message handler completes. This means that if a handler takes an extended time (e.g., 30 seconds), the warning won’t appear until it finishes.
I have attempted to implement a solution that handles this case in real-time but haven't been able to get it working as intended yet.

**Request for Feedback:**

If the current implementation is satisfactory, I would appreciate feedback on how to improve the async version for real-time warnings.

2024-08-23 11:04 UTC, willmcgugan requested changes
A few requests...

Could you add a test?

Put a pause in the message handler, and check the message is written as expected.

2024-08-23 11:04 UTC, willmcgugan commented on src/textual/message_pump.py
> +                    log.warning.verbosity(message.verbose)(
This is only in debug mode, so I don't think we need to worry about verbosity.

2024-08-23 11:04 UTC, willmcgugan commented on src/textual/message_pump.py
> +                        ">>>",
I don't think we need the ">>>", that was just to indicate a message being sent.

2024-08-23 11:04 UTC, willmcgugan commented on src/textual/message_pump.py
> +                        "\nTo avoid screen freezes use the [work decorator](/guide/workers/#workers)"
This goes to the textual console, which doesn't support Markdown syntax. Suggest simply "Consider using a worker."

2024-08-28 07:31 UTC, Zimzozaur commented
I’ve updated the code based on your suggestions. However, I’m still unsure how to test the logging. I’ve reviewed the documentation and other tests but could use some guidance.

2024-09-05 06:04 UTC, darrenburns commented
Hey @Zimzozaur, could you run `make format` to format the code? If you want to do this automatically you can run `pre-commit install` and it'll run everything you need (not including the tests) automatically when you `git commit`.

2024-09-06 08:58 UTC, Zimzozaur commented
Hey @darrenburns after few tries and some learning, I ran it. Now Black is happy 🙂

2024-09-09 09:13 UTC, darrenburns commented
Thanks @Zimzozaur!

To be honest this is very difficult to test, but here's some guidance:

- You'll probably want to reduce the slow threshold env var value for the test - `monkeypatch.setenv("TEXTUAL_SLOW_THRESHOLD", "50")`. Search the codebase for `monkeypatch.setenv` for examples.
- You'll need to create a subclass of `App` - there are many examples of this in tests.
- Inside `App.on_mount`, you'll need to post a message e.g. `self.post_message(MySlowMessage)`.
- Inside the handler for that message (an `async` method `App.on_my_slow_message`), add an `asyncio.sleep` call. This will allow us to simulate what happens when a handler is slow.
- At this point it becomes a bit tricky as we need to swap out Textual's logger for our own one which we can query to inspect what gets logged. Looking at the code here - I think `message_pump.py` probably needs a small change to make this easier, but for now you could set the `_logger` attribute on your `App` to a `Mock` object, the check the values `call_args_list` to ensure that the "warning" log was called with the expected string.

2024-09-11 13:49 UTC, Zimzozaur commented
@willmcgugan, @darrenburns I didn't respond because I got sick. I do not mind if you add the tests. For the first good issue, this part is quite hard. 

When you merge changes, can I write/try to implement async from the bonus points section? 

2024-09-11 14:57 UTC, willmcgugan commented
No worries. Hope you are feeling better. Feel free to tackle the bonus points!

2024-09-11 14:57 UTC, merged