Initial layout guide stuff
Textualize/textual pull request #748
Opened 2022-09-08 14:09 UTC by darrenburns

2022-09-08 14:30 UTC, willmcgugan commented on docs/guide/layout.md
> +TODO: ??? Do we draw attention to the fact that we had to set height 100%, for the widgets to fill the height of their parent? This wasn't required in the vertical example, so might be worth explaini
Yes, I think so.

2022-09-08 14:31 UTC, willmcgugan commented on docs/guide/layout.md
> +TODO: The sections above show layouts in isolation. Maybe we should mention how we can combine multiple layouts in a single app?
Yes, good idea. A simple example combining layouts would be great.

2022-09-08 17:01 UTC, darrenburns commented
@willmcgugan Feel free to review down to "Adjusting cell spans"

2022-09-15 09:04 UTC, willmcgugan requested changes
This is great! We'll probably tighten up the prose a little. It's a little wordy in places, particularly in grid (which I know is harder to describe). 

Only one technical thing to mention. The grid-size declaration can take two integer. With two values it sets a fixed columns and rows, and you don't get that auto new row behaviour.

Could you add that detail, and we should be good to merge.

We'll do another pass on all the docs to pick up typos / grammar later.

2022-09-15 14:28 UTC, merged