Minimise rendering when text-opacity/opacity is zero
Textualize/textual pull request #774
Opened 2022-09-14 17:05 UTC by darrenburns

* For text-opacity we no longer render text as the same colour as the background. We instead render empty cells of the same cell length. This will also improve the "minimum contrast" situation.
* For opacity, the compositor will ignore widgets with 0 opacity (same as when visibility is "hidden" - by still reserving space for the widget).

2022-09-15 08:40 UTC, willmcgugan requested changes
Looks good, but I'd like to go the extra mile to squeeze a few more cycles out of this.

2022-09-15 08:40 UTC, willmcgugan commented on src/textual/renderables/text_opacity.py
> +            if opacity > 0:
This condition will be constant in the loop. If we move it outside of the loop then we can write an optimized version for the case of opacity == 0

2022-09-15 08:40 UTC, willmcgugan commented on src/textual/_compositor.py
> +        def is_visible(widget: Widget) -> bool:
This is a fairly tight loop.

Humor me and unroll the code in is_visible. Essentially replace the properties with immediate code, so it makes no implicity function calls.

2022-09-15 11:20 UTC, darrenburns commented
@willmcgugan Made those changes, also fixed a link in the docs.

2022-09-20 09:50 UTC, willmcgugan approved these changes

2022-09-20 09:50 UTC, merged