Support for key aliases, key handling tests
Textualize/textual pull request #852
Opened 2022-10-07 10:30 UTC by darrenburns

- Adds support for key aliases.
- Adds message pump unit tests for dispatching keys and ensuring handlers are called as expected.

If multiple handlers exist for a single key, an exception is raised since we can't know which one the author meant.

Also adds the exception logic to the case where public and private handlers exist for the same key press.

Example output for conflicting handlers:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/5740731/194534204-6457d8c4-d676-4fc2-827b-5f91ec6b1d3f.png">

2022-10-10 09:34 UTC, willmcgugan requested changes

2022-10-10 09:36 UTC, darrenburns commented on src/textual/message.py
> +    async def bubble_to(self, widget: MessagePump) -> None:
It's used outside of this class

2022-10-10 09:41 UTC, willmcgugan commented on src/textual/message.py
> +    async def bubble_to(self, widget: MessagePump) -> None:
I think for our purposes, anything that a Textual app developer doesn't need to use should be private. It also prevents the method from being exposed in the docs.

2022-10-11 13:59 UTC, willmcgugan requested changes
Looks good. Just one request.

2022-10-11 14:19 UTC, willmcgugan commented
@darrenburns Can be drop the property now?

2022-10-11 14:24 UTC, darrenburns commented
@willmcgugan Yep, sorry, missed that.

2022-10-11 14:38 UTC, willmcgugan approved these changes
LGTM

2022-10-11 14:39 UTC, merged